# Generated by Django 5.2.6 on 2025-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_country_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_profile_images/"
            ),
        ),
    ]
