# Generated by Django 5.2.6 on 2025-10-21 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userreferral"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreferral",
            old_name="referral_code",
            new_name="referrer_code",
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrers",
                to="accounts.userreferral",
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
