# Generated by Django 5.2.6 on 2025-10-21 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_referral_code_userreferral_referrer_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreferral",
            old_name="referrer_code",
            new_name="referral_code",
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
