# Generated by Django 5.2.6 on 2025-10-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_referrer_code_userreferral_referral_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreferral",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_users",
                to="accounts.userreferral",
            ),
        ),
    ]
