# Generated by Django 5.2.6 on 2025-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userreferral_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreferral",
            name="reward_given",
            field=models.BooleanField(default=False),
        ),
    ]
