# Generated by Django 5.2.6 on 2025-11-13 11:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userreferral_reward_given"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                max_length=255, validators=[accounts.models.validate_full_name]
            ),
        ),
    ]
