# Generated by Django 5.2.6 on 2025-11-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreferral",
            old_name="referral_code",
            new_name="referrer_code",
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
