# Generated by Django 5.2.6 on 2025-11-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_email"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", True)),
                fields=("email",),
                name="unique_verified_user_email",
            ),
        ),
    ]
