# Generated by Django 5.2.6 on 2025-09-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="Admin_categories",
        ),
    ]
