# Generated by Django 5.2.6 on 2025-09-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="admin_categories",
        ),
    ]
