# Generated by Django 5.2.6 on 2025-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Discount (eg: 10.50 for 10.5%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
