# Generated by Django 5.2.6 on 2025-09-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_category_discount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
