# Generated by Django 5.2.6 on 2025-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
