# Generated by Django 5.2.6 on 2025-10-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
