# Generated by Django 5.2.6 on 2025-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="promo_image",
            field=models.ImageField(blank=True, null=True, upload_to="featured_promo/"),
        ),
    ]
