# Generated by Django 5.2.6 on 2025-10-15 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0007_alter_category_slug"),
        ("products", "0008_productvariant_stock_non_negative"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("category", "Category Offer"),
                            ("product", "Product Offer"),
                            ("referral", "Referral Offer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_peradmin_offer_listcent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter discount in percentage (e.g, 10 for 10%)",
                        max_digits=5,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="offers", to="category.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="offers", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "ordering": ["-created_at"],
            },
        ),
    ]
