# Generated by Django 5.2.6 on 2025-10-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="discount_peradmin_offer_listcent",
            new_name="discount_percent",
        ),
    ]
