# Generated by Django 5.2.6 on 2025-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "offers",
            "0002_rename_discount_peradmin_offer_listcent_offer_discount_percent",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
