# Generated by Django 5.2.6 on 2025-10-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_alter_offer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
