# Generated by Django 5.2.6 on 2025-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_alter_offer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[("category", "Category Offer"), ("product", "Product Offer")],
                max_length=20,
            ),
        ),
    ]
