# Generated by Django 5.2.6 on 2025-10-28 17:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="IN"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=6),
        ),
    ]
