# Generated by Django 5.2.6 on 2025-10-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_address_mobile_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
