# Generated by Django 5.2.6 on 2025-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
