# Generated by Django 5.2.6 on 2025-09-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_sub_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="sub_total",
            new_name="subtotal",
        ),
    ]
