# Generated by Django 5.2.6 on 2025-09-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_sub_total_order_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                    ("wallet", "Wallet"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
