# Generated by Django 5.2.6 on 2025-09-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                    ("wallet", "Wallet"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
