# Generated by Django 5.2.6 on 2025-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
