# Generated by Django 5.2.6 on 2025-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_orderitem_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
