# Generated by Django 5.2.6 on 2025-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_orderitem_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
