# Generated by Django 5.2.6 on 2025-10-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_alter_orderitem_return_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="returned_reason",
            new_name="return_reason",
        ),
    ]
