# Generated by Django 5.2.6 on 2025-10-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_rename_returned_reason_orderitem_return_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="returned_at",
            new_name="return_at",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
