# Generated by Django 5.2.6 on 2025-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_rename_returned_at_orderitem_return_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
