# Generated by Django 5.2.6 on 2025-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_order_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
