# Generated by Django 5.2.6 on 2025-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_alter_order_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="return_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
