# Generated by Django 5.2.6 on 2025-10-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_order_payment_status_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                    ("wallet", "Wallet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
