# Generated by Django 5.2.6 on 2025-10-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_order_coupon_discount_order_discount_amount"),
        ("products", "0008_productvariant_stock_non_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orderitems",
                to="products.productvariant",
            ),
        ),
    ]
