# Generated by Django 5.2.6 on 2025-10-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_alter_orderitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
