# Generated by Django 5.2.6 on 2025-10-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_order_original_total"),
        ("products", "0013_alter_productvariant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="products.productvariant",
            ),
        ),
    ]
