# Generated by Django 5.2.6 on 2025-10-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_alter_orderitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
    ]
