# Generated by Django 5.2.6 on 2025-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_order_is_refunded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                    ("partially_cancelled", "Partially cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
