# Generated by Django 5.2.6 on 2025-11-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
