# Generated by Django 5.2.6 on 2025-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_order_amount_paid_order_refunded_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
    ]
