# Generated by Django 5.2.6 on 2025-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_min_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
