# Generated by Django 5.2.6 on 2025-11-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_order_coupon_code_order_coupon_min_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
