# Generated by Django 5.2.6 on 2025-11-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_alter_order_coupon_code"),
        ("products", "0014_alter_productvariant_max_quantity_per_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="price_at_purchase",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="flavor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="weight_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderitems",
                to="products.productvariant",
            ),
        ),
    ]
