# Generated by Django 5.2.6 on 2025-11-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0036_rename_price_orderitem_price_at_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="order_items/"),
        ),
    ]
