# Generated by Django 5.2.6 on 2025-11-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_orderitem_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_image",
        ),
    ]
