# # Generated by Django 5.2.6 on 2025-09-16 14:28

# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ("basket", "0001_initial"),
#         ("products", "0001_initial"),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name="basketitem",
#             name="variant",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 to="products.productvariant",
#             ),
#         ),
#     ]



# Generated by Django 5.2.6 on 2025-09-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basket", "0001_initial"),
        ("products", "0001_initial"),  # Corrected dependency
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
            ),
        ),
    ]