# Generated by Django 5.2.6 on 2025-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="from_wishlist",
            field=models.BooleanField(default=False),
        ),
    ]
