# Generated by Django 5.2.6 on 2025-09-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="product_image",
        ),
    ]
