# Generated by Django 5.2.6 on 2025-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_table_alter_productimage_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categoryId",
            new_name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="products_image",
        ),
    ]
