# Generated by Django 5.2.6 on 2025-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_categoryid_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
