# Generated by Django 5.2.6 on 2025-09-18 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_flavor_weight_remove_product_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flavor",
            old_name="name",
            new_name="flavor",
        ),
        migrations.RenameField(
            model_name="weight",
            old_name="name",
            new_name="weight",
        ),
        migrations.AddField(
            model_name="flavor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weight",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
