# Generated by Django 5.2.6 on 2025-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_rename_name_flavor_flavor_rename_name_weight_weight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
