# Generated by Django 5.2.6 on 2025-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
