# Generated by Django 5.2.6 on 2025-09-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
