# Generated by Django 5.2.6 on 2025-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productvariant_is_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_quantity_per_order",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
