# Generated by Django 5.2.6 on 2025-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_max_quantity_per_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="max_quantity_per_order",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
