# Generated by Django 5.2.6 on 2025-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvariant_max_quantity_per_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="stock_non_negative"
            ),
        ),
    ]
