# Generated by Django 5.2.6 on 2025-10-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_slug"),
        ("products", "0008_productvariant_stock_non_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="category.category",
            ),
        ),
    ]
