# Generated by Django 5.2.6 on 2025-10-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_productvariant_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "flavor", "weight")},
        ),
    ]
