# Generated by Django 5.2.6 on 2025-10-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_productvariant_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
    ]
