# Generated by Django 5.2.6 on 2025-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productvariant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="max_quantity_per_order",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
